name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        php: [8.2, 8.1]
        laravel: [10.*, 9.*]
        dependency-version: [prefer-stable]
        include:
          -   laravel: 10.*
              testbench: 8.*
          -   laravel: 9.*
              testbench: 7.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v3

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, pcntl
            coverage: none

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
          env:
            COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      -   name: Execute tests
          run: vendor/bin/pest
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            POSTMARK_SERVER_TOKEN: ${{ secrets.POSTMARK_SERVER_TOKEN }}
            SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
